channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=22.2.2
- pip:
  - mlflow
  - boto3==1.24.70
  - cffi==1.15.1
  - defusedxml==0.7.1
  - dill==0.3.5.1
  - keras==2.8.0
  - pandas==1.4.4
  - pillow==9.2.0
  - scipy==1.9.1
  - tensorflow==2.8.2
name: mlflow-env
